spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://localhost:4317

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/