scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9491' ]
        labels:
          application: 'Users service'
      - targets: [ 'host.docker.internal:9492' ]
        labels:
          application: 'Company service'
      - targets: [ 'host.docker.internal:9493' ]
        labels:
          application: 'Notification service'