server:
  port: 0
spring:
  application:
    name: company

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://localhost:4317